'use client';

import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/redux/configStore";
import 'bootstrap/dist/css/bootstrap.min.css'; 
import { NotificationContainer } from "react-notifications";
import "react-notifications/lib/notifications.css";

import Header from '@/component/Header'
import Footer from "@/component/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Tarun Machine Test",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>
          <Header />
          {children}
          <Footer />

          <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            async
          />
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
            async
          />
          <NotificationContainer />
        </body>
      </html>
    </Provider>
  );
}
